// frontend/Angular/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { Subscription, Payment, Notification } from '../../core/models';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-content">
      @if (loading()) {
        <div class="loader"><div class="spinner"></div></div>
      } @else {
        <div class="grid-4 mb-20">
          <div class="stat">
            <div class="stat-label">Subscriptions</div>
            <div class="stat-value" style="color:var(--accent2)">{{ subs().length }}</div>
          </div>
          <div class="stat">
            <div class="stat-label">Est. monthly</div>
            <div class="stat-value">€{{ monthlyTotal() | number:'1.2-2' }}</div>
          </div>
          <div class="stat">
            <div class="stat-label">Total spent</div>
            <div class="stat-value" style="color:var(--green)">{{ totalSpent() | number:'1.2-2' }}</div>
          </div>
          <div class="stat">
            <div class="stat-label">Unread</div>
            <div class="stat-value" [style.color]="unreadCount() > 0 ? 'var(--yellow)' : 'var(--text)'">
              {{ unreadCount() }}
            </div>
          </div>
        </div>

        <div class="grid-2">
          <div class="card">
            <div class="card-title">📦 Recent subscriptions</div>
            @if (subs().length === 0) {
              <div class="empty"><div class="empty-icon">📦</div>No subscriptions yet</div>
            } @else {
              @for (s of subs().slice(0,4); track s.id) {
                <div style="display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid var(--border)">
                  <div>
                    <div style="font-weight:500">{{ s.plan?.service?.name }}</div>
                    <div style="font-size:12px;color:var(--muted)">{{ s.plan?.name }} · {{ s.plan?.billingPeriod }}</div>
                  </div>
                  <div style="text-align:right">
                    <div style="font-weight:600">{{ s.plan?.price }} {{ s.plan?.currency }}</div>
                    <span class="badge" [class]="s.autoRenew ? 'badge-green' : 'badge-muted'">
                      {{ s.autoRenew ? 'Auto-renew' : 'Manual' }}
                    </span>
                  </div>
                </div>
              }
            }
          </div>

          <div class="card">
            <div class="card-title">🔔 Recent notifications</div>
            @if (notifs().length === 0) {
              <div class="empty"><div class="empty-icon">🔔</div>All caught up!</div>
            } @else {
              @for (n of notifs().slice(0,5); track n.id) {
                <div class="notif-item">
                  <div class="notif-dot" [class.read]="!n.isUnread"></div>
                  <div style="flex:1;font-size:13px">{{ n.message }}</div>
                  <div class="notif-time">{{ n.createdAt | date:'shortDate' }}</div>
                </div>
              }
            }
          </div>
        </div>
      }
    </div>
  `
})
export class DashboardComponent implements OnInit {
  private api   = inject(ApiService);
  private toast = inject(ToastService);

  loading = signal(true);
  subs    = signal<Subscription[]>([]);
  payments = signal<Payment[]>([]);
  notifs  = signal<Notification[]>([]);

  monthlyTotal() {
    return this.subs().reduce((acc, s) => {
      const p = s.plan?.price ?? 0;
      if (s.plan?.billingPeriod === 'monthly') return acc + +p;
      if (s.plan?.billingPeriod === 'yearly')  return acc + +p / 12;
      return acc;
    }, 0);
  }
  totalSpent()  { return this.payments().reduce((a, p) => a + +p.amount, 0); }
  unreadCount() { return this.notifs().filter(n => n.isUnread).length; }

  ngOnInit() {
    forkJoin([this.api.getSubscriptions(), this.api.getPayments(), this.api.getNotifications()]).subscribe({
      next: ([s, p, n]) => { this.subs.set(s); this.payments.set(p); this.notifs.set(n); },
      error: e => this.toast.error(e.error?.message ?? 'Error'),
      complete: () => this.loading.set(false)
    });
  }
}

// frontend/React/src/pages/Dashboard.jsx
import { useEffect, useState } from 'react'
import { subsApi, paymentsApi, notificationsApi } from '../api'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { Loader, Empty, Icon, Icons } from '../components/ui'

export default function Dashboard() {
  const { token } = useAuth()
  const { toast } = useToast()
  const [subs, setSubs] = useState([])
  const [payments, setPayments] = useState([])
  const [notifs, setNotifs] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      subsApi.getAll(token),
      paymentsApi.getAll(token),
      notificationsApi.getAll(token),
    ])
      .then(([s, p, n]) => { setSubs(s || []); setPayments(p || []); setNotifs(n || []) })
      .catch(e => toast(e.message, 'error'))
      .finally(() => setLoading(false))
  }, [])

  if (loading) return <Loader />

  const totalMonthly = subs.reduce((acc, s) => {
    const price = parseFloat(s.plan?.price || 0)
    if (s.plan?.billingPeriod === 'monthly') return acc + price
    if (s.plan?.billingPeriod === 'yearly')  return acc + price / 12
    return acc
  }, 0)

  const unread     = notifs.filter(n => n.isUnread).length
  const totalSpent = payments.reduce((a, p) => a + parseFloat(p.amount || 0), 0)

  return (
    <div className="content">
      <div className="grid-4" style={{ marginBottom: 20 }}>
        <div className="stat">
          <div className="stat-label">Subscriptions</div>
          <div className="stat-value" style={{ color: 'var(--accent2)' }}>{subs.length}</div>
        </div>
        <div className="stat">
          <div className="stat-label">Est. monthly</div>
          <div className="stat-value">€{totalMonthly.toFixed(2)}</div>
        </div>
        <div className="stat">
          <div className="stat-label">Total spent</div>
          <div className="stat-value" style={{ color: 'var(--green)' }}>{totalSpent.toFixed(2)}</div>
        </div>
        <div className="stat">
          <div className="stat-label">Unread</div>
          <div className="stat-value" style={{ color: unread > 0 ? 'var(--yellow)' : 'var(--text)' }}>{unread}</div>
        </div>
      </div>

      <div className="grid-2">
        <div className="card">
          <div className="card-title"><Icon d={Icons.sub} /> Recent subscriptions</div>
          {subs.length === 0 ? (
            <Empty icon="📦" text="No subscriptions yet" />
          ) : (
            subs.slice(0, 4).map(s => (
              <div key={s.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: '1px solid var(--border)' }}>
                <div>
                  <div style={{ fontWeight: 500 }}>{s.plan?.service?.name}</div>
                  <div style={{ fontSize: 12, color: 'var(--muted)' }}>{s.plan?.name} · {s.plan?.billingPeriod}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontWeight: 600 }}>{s.plan?.price} {s.plan?.currency}</div>
                  <span className={`badge ${s.autoRenew ? 'badge-green' : 'badge-muted'}`}>
                    {s.autoRenew ? 'Auto-renew' : 'Manual'}
                  </span>
                </div>
              </div>
            ))
          )}
        </div>

        <div className="card">
          <div className="card-title"><Icon d={Icons.notif} /> Recent notifications</div>
          {notifs.length === 0 ? (
            <Empty icon="🔔" text="All caught up!" />
          ) : (
            notifs.slice(0, 5).map(n => (
              <div key={n.id} className="notif-item">
                <div className={`notif-dot ${n.isUnread ? '' : 'read'}`} />
                <div style={{ flex: 1, fontSize: 13 }}>{n.message}</div>
                <div className="notif-time">{new Date(n.createdAt).toLocaleDateString()}</div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}
