// frontend/React/src/pages/Notifications.jsx
import { useState, useEffect, useCallback } from 'react'
import { notificationsApi } from '../api'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { Loader, Empty, Icon, Icons } from '../components/ui'

export default function Notifications() {
  const { token } = useAuth()
  const { toast } = useToast()
  const [notifs, setNotifs] = useState([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    try {
      const data = await notificationsApi.getAll(token)
      setNotifs(data || [])
    } catch (e) { toast(e.message, 'error') }
    finally { setLoading(false) }
  }, [token])

  useEffect(() => { load() }, [load])

  async function markRead(id) {
    try {
      await notificationsApi.markAsRead(id, token)
      load()
    } catch (e) { toast(e.message, 'error') }
  }

  if (loading) return <Loader />

  const unread = notifs.filter(n => n.isUnread)
  const read   = notifs.filter(n => !n.isUnread)

  return (
    <div className="content">
      {notifs.length === 0 && <Empty icon="🔔" text="No notifications" />}

      {unread.length > 0 && (
        <>
          <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12 }}>
            Unread · {unread.length}
          </div>
          {unread.map(n => (
            <div key={n.id} className="notif-item" style={{ borderColor: 'color-mix(in srgb, var(--accent) 30%, transparent)' }}>
              <div className="notif-dot" />
              <div style={{ flex: 1, fontSize: 13 }}>{n.message}</div>
              <div className="flex-gap">
                <div className="notif-time">{new Date(n.createdAt).toLocaleDateString()}</div>
                <button className="btn btn-ghost btn-sm" onClick={() => markRead(n.id)} title="Mark as read">
                  <Icon d={Icons.check} size={12} />
                </button>
              </div>
            </div>
          ))}
          {read.length > 0 && <div className="divider" />}
        </>
      )}

      {read.length > 0 && (
        <>
          <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12 }}>
            Read
          </div>
          {read.map(n => (
            <div key={n.id} className="notif-item" style={{ opacity: 0.6 }}>
              <div className="notif-dot read" />
              <div style={{ flex: 1, fontSize: 13 }}>{n.message}</div>
              <div className="notif-time">{new Date(n.createdAt).toLocaleDateString()}</div>
            </div>
          ))}
        </>
      )}
    </div>
  )
}

// frontend/Angular/src/app/features/notifications/notifications.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { Notification } from '../../core/models';

@Component({
  selector: 'app-notifications',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-content">
      @if (loading()) {
        <div class="loader"><div class="spinner"></div></div>
      } @else if (notifs().length === 0) {
        <div class="empty"><div class="empty-icon">🔔</div>No notifications</div>
      } @else {

        @if (unread().length > 0) {
          <div class="section-label">Unread · {{ unread().length }}</div>
          @for (n of unread(); track n.id) {
            <div class="notif-item" style="border-color:color-mix(in srgb,var(--accent) 30%,transparent)">
              <div class="notif-dot"></div>
              <div style="flex:1;font-size:13px">{{ n.message }}</div>
              <div class="flex-gap">
                <div class="notif-time">{{ n.createdAt | date:'shortDate' }}</div>
                <button class="btn btn-ghost btn-sm" (click)="markRead(n.id)" title="Mark as read">✓</button>
              </div>
            </div>
          }
          @if (read().length > 0) { <div class="divider"></div> }
        }

        @if (read().length > 0) {
          <div class="section-label">Read</div>
          @for (n of read(); track n.id) {
            <div class="notif-item" style="opacity:.6">
              <div class="notif-dot read"></div>
              <div style="flex:1;font-size:13px">{{ n.message }}</div>
              <div class="notif-time">{{ n.createdAt | date:'shortDate' }}</div>
            </div>
          }
        }

      }
    </div>
  `
})
export class NotificationsComponent implements OnInit {
  private api   = inject(ApiService);
  private toast = inject(ToastService);

  loading = signal(true);
  notifs  = signal<Notification[]>([]);
  unread  = computed(() => this.notifs().filter(n => n.isUnread));
  read    = computed(() => this.notifs().filter(n => !n.isUnread));

  ngOnInit() { this.load(); }

  load() {
    this.api.getNotifications().subscribe({
      next: d => this.notifs.set(d),
      error: e => this.toast.error(e.error?.message ?? 'Error'),
      complete: () => this.loading.set(false)
    });
  }

  markRead(id: number) {
    this.api.markAsRead(id).subscribe({
      next: () => this.load(),
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }
}
