// frontend/React/src/pages/Subscriptions.jsx
import { useState, useEffect, useCallback } from 'react'
import { subsApi, servicesApi, devicesApi } from '../api'
import { useAuth } from '../context/AuthContext'
import { useToast } from '../context/ToastContext'
import { Loader, Empty, Modal, Icon, Icons } from '../components/ui'

export default function Subscriptions() {
  const { token } = useAuth()
  const { toast } = useToast()
  const [subs, setSubs] = useState([])
  const [loading, setLoading] = useState(true)
  const [showCreate, setShowCreate] = useState(false)
  const [showEvents, setShowEvents] = useState(null)
  const [showDevices, setShowDevices] = useState(null) // subscription id
  const [events, setEvents] = useState([])
  const [subDevices, setSubDevices] = useState([])     // devices attached to sub
  const [myDevices, setMyDevices] = useState([])       // all user devices

  // create form
  const [services, setServices] = useState([])
  const [plans, setPlans] = useState([])
  const [selectedService, setSelectedService] = useState('')
  const [planId, setPlanId] = useState('')
  const [autoRenew, setAutoRenew] = useState(true)

  const load = useCallback(async (showLoader = true) => {
    if (showLoader) setLoading(true)
    try {
      const [s, sv] = await Promise.all([subsApi.getAll(token), servicesApi.getAll(token)])
      setSubs(s || [])
      setServices(sv || [])
    } catch (e) {
      toast(e.message, 'error')
    } finally {
      setLoading(false)
    }
  }, [token])

  useEffect(() => { load() }, [load])

  async function loadPlans(serviceId) {
    setSelectedService(serviceId)
    setPlanId('')
    if (!serviceId) { setPlans([]); return }
    try {
      const data = await servicesApi.getPlans(serviceId, token)
      setPlans(data || [])
    } catch (e) { toast(e.message, 'error') }
  }

  async function create() {
    try {
      await subsApi.create({ planId: parseInt(planId), autoRenew }, token)
      toast('Subscription created')
      setShowCreate(false)
      setSelectedService(''); setPlanId(''); setPlans([])
      await load(false)
    } catch (e) { toast(e.message, 'error') }
  }

  async function toggleAutoRenew(id) {
    try {
      await subsApi.toggleAutoRenew(id, token)
      toast('Auto-renew updated')
      await load(false)
    } catch (e) { toast(e.message, 'error') }
  }

  async function cancel(id) {
    if (!confirm('Cancel this subscription?')) return
    try {
      await subsApi.cancel(id, token)
      toast('Subscription cancelled')
      await load(false)
    } catch (e) { toast(e.error?.message || e.message, 'error') }
  }

  async function viewEvents(id) {
    try {
      const data = await subsApi.getEvents(id, token)
      setEvents(data || [])
      setShowEvents(id)
    } catch (e) { toast(e.message, 'error') }
  }

  // ── Devices attach/detach ─────────────────────────────────────────────────
  async function openDevices(subId) {
    try {
      const [attached, all] = await Promise.all([
        devicesApi.getBySubscription(subId, token),
        devicesApi.getAll(token),
      ])
      setSubDevices(attached || [])
      setMyDevices(all || [])
      setShowDevices(subId)
    } catch (e) { toast(e.message, 'error') }
  }

  async function attach(subId, deviceId) {
    try {
      await devicesApi.attach(subId, { deviceId }, token)
      toast('Device attached')
      const data = await devicesApi.getBySubscription(subId, token)
      setSubDevices(data || [])
    } catch (e) { toast(e.error?.message || e.message, 'error') }
  }

  async function detach(subId, deviceId) {
    try {
      await devicesApi.detach(subId, deviceId, token)
      toast('Device detached')
      const data = await devicesApi.getBySubscription(subId, token)
      setSubDevices(data || [])
    } catch (e) { toast(e.error?.message || e.message, 'error') }
  }

  const attachedIds = new Set(subDevices.map(d => d.id))
  const sub = subs.find(s => s.id === showDevices)
  const maxDevices = sub?.plan?.maxDevices ?? Infinity

  if (loading) return <Loader />

  return (
    <div className="content">
      <div className="flex-between mb-16">
        <div style={{ fontSize: 13, color: 'var(--muted)' }}>
          {subs.length} subscription{subs.length !== 1 ? 's' : ''}
        </div>
        <button className="btn btn-primary" onClick={() => setShowCreate(true)}>
          <Icon d={Icons.plus} /> New subscription
        </button>
      </div>

      {subs.length === 0 ? (
        <Empty icon="📦" text="No subscriptions yet."
          action={<button className="btn btn-primary" onClick={() => setShowCreate(true)}>Add subscription</button>}
        />
      ) : (
        <div className="stack">
          {subs.map(s => (
            <div key={s.id} className="sub-card">
              <div style={{ flex: 1 }}>
                <div className="flex-gap" style={{ marginBottom: 4, flexWrap: 'wrap' }}>
                  <div className="sub-name">{s.plan?.service?.name}</div>
                  <span className="badge badge-purple">{s.plan?.name}</span>
                  <span className={`badge ${s.autoRenew ? 'badge-green' : 'badge-muted'}`}>
                    {s.autoRenew ? 'Auto-renew on' : 'Auto-renew off'}
                  </span>
                </div>
                <div className="sub-meta">
                  {s.plan?.maxDevices ? `Up to ${s.plan.maxDevices} devices` : 'Unlimited devices'} · Billed {s.plan?.billingPeriod}
                </div>
                <div className="sub-actions">
                  <button className="btn btn-ghost btn-sm" onClick={() => toggleAutoRenew(s.id)}>
                    <Icon d={Icons.refresh} size={12} /> Toggle auto-renew
                  </button>
                  <button className="btn btn-ghost btn-sm" onClick={() => openDevices(s.id)}>
                    📱 Devices
                  </button>
                  <button className="btn btn-ghost btn-sm" onClick={() => viewEvents(s.id)}>
                    History
                  </button>
                  <button className="btn btn-danger btn-sm" onClick={() => cancel(s.id)}>
                    <Icon d={Icons.x} size={12} /> Cancel
                  </button>
                </div>
              </div>
              <div style={{ textAlign: 'right', flexShrink: 0 }}>
                <div className="sub-price">{s.plan?.price} {s.plan?.currency}</div>
                <div className="sub-period">/{s.plan?.billingPeriod}</div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create modal */}
      {showCreate && (
        <Modal title="New subscription" onClose={() => setShowCreate(false)} footer={
          <>
            <button className="btn btn-ghost" onClick={() => setShowCreate(false)}>Cancel</button>
            <button className="btn btn-primary" onClick={create} disabled={!planId}>Create</button>
          </>
        }>
          <div className="form-group">
            <label className="form-label">Service</label>
            <select className="form-select" value={selectedService} onChange={e => loadPlans(e.target.value)}>
              <option value="">Select a service…</option>
              {services.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          {plans.length > 0 && (
            <div className="form-group">
              <label className="form-label">Plan</label>
              <select className="form-select" value={planId} onChange={e => setPlanId(e.target.value)}>
                <option value="">Select a plan…</option>
                {plans.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.name} — {p.price} {p.currency}/{p.billingPeriod}
                  </option>
                ))}
              </select>
            </div>
          )}
          <div className="form-group">
            <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
              <input type="checkbox" checked={autoRenew} onChange={e => setAutoRenew(e.target.checked)} />
              <span style={{ fontSize: 13 }}>Enable auto-renew</span>
            </label>
          </div>
        </Modal>
      )}

      {/* Events modal */}
      {showEvents !== null && (
        <Modal title="Subscription history" onClose={() => setShowEvents(null)}>
          {events.length === 0 ? <Empty icon="📋" text="No events recorded" /> : (
            <div className="table-wrap">
              <table>
                <thead><tr><th>Event</th><th>Date</th><th>Days</th></tr></thead>
                <tbody>
                  {events.map(e => (
                    <tr key={e.id}>
                      <td><span className="badge badge-purple">{e.eventType}</span></td>
                      <td>{e.eventDate}</td>
                      <td>{e.days ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Modal>
      )}

      {/* Devices modal */}
      {showDevices !== null && (
        <Modal title={`Devices — ${sub?.plan?.service?.name}`} onClose={() => setShowDevices(null)}>
          {/* Attached devices */}
          {subDevices.length === 0 ? (
            <Empty icon="📱" text="No devices attached yet" />
          ) : (
            <div style={{ marginBottom: 16 }}>
              <div className="section-label" style={{ marginBottom: 8 }}>Attached</div>
              {subDevices.map(d => (
                <div key={d.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
                  <div>
                    <div style={{ fontWeight: 500, fontSize: 13 }}>{d.name}</div>
                    <div style={{ fontSize: 11, color: 'var(--muted)' }}>{d.type}</div>
                  </div>
                  <button className="btn btn-danger btn-sm" onClick={() => detach(showDevices, d.id)}>
                    Detach
                  </button>
                </div>
              ))}
            </div>
          )}

          {/* Available to attach */}
          {myDevices.filter(d => !attachedIds.has(d.id)).length > 0 && (
            <>
              <div className="divider" />
              <div className="section-label" style={{ marginBottom: 8 }}>
                Available
                {maxDevices !== Infinity && (
                  <span style={{ color: 'var(--muted)', fontWeight: 400, marginLeft: 8 }}>
                    ({subDevices.length}/{maxDevices} slots used)
                  </span>
                )}
              </div>
              {myDevices.filter(d => !attachedIds.has(d.id)).map(d => (
                <div key={d.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
                  <div>
                    <div style={{ fontWeight: 500, fontSize: 13 }}>{d.name}</div>
                    <div style={{ fontSize: 11, color: 'var(--muted)' }}>{d.type}</div>
                  </div>
                  <button
                    className="btn btn-primary btn-sm"
                    onClick={() => attach(showDevices, d.id)}
                    disabled={maxDevices !== Infinity && subDevices.length >= maxDevices}
                  >
                    Attach
                  </button>
                </div>
              ))}
            </>
          )}
        </Modal>
      )}
    </div>
  )
}

// frontend/Angular/src/app/features/subscriptions/subscriptions.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { Subscription, SubscriptionEvent, Service, Plan, Device } from '../../core/models';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-subscriptions',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-content">
      <div class="flex-between mb-16">
        <div style="font-size:13px;color:var(--muted)">{{ subs().length }} subscription(s)</div>
        <button class="btn btn-primary" (click)="openCreate()">＋ New subscription</button>
      </div>

      @if (loading()) {
        <div class="loader"><div class="spinner"></div></div>
      } @else if (subs().length === 0) {
        <div class="empty">
          <div class="empty-icon">📦</div>
          No subscriptions yet.
          <div style="margin-top:16px"><button class="btn btn-primary" (click)="openCreate()">Add subscription</button></div>
        </div>
      } @else {
        <div class="stack">
          @for (s of subs(); track s.id) {
            <div class="sub-card">
              <div style="flex:1">
                <div class="flex-gap" style="margin-bottom:4px;flex-wrap:wrap">
                  <div class="sub-name">{{ s.plan?.service?.name }}</div>
                  <span class="badge badge-purple">{{ s.plan?.name }}</span>
                  <span class="badge" [class]="s.autoRenew ? 'badge-green' : 'badge-muted'">
                    {{ s.autoRenew ? 'Auto-renew on' : 'Auto-renew off' }}
                  </span>
                </div>
                <div class="sub-meta">
                  {{ s.plan?.maxDevices ? 'Up to ' + s.plan.maxDevices + ' devices' : 'Unlimited devices' }}
                  · Billed {{ s.plan?.billingPeriod }}
                </div>
                <div class="sub-actions">
                  <button class="btn btn-ghost btn-sm" (click)="toggle(s.id)">⟳ Toggle auto-renew</button>
                  <button class="btn btn-ghost btn-sm" (click)="openDevices(s.id, s)">📱 Devices</button>
                  <button class="btn btn-ghost btn-sm" (click)="viewEvents(s.id)">History</button>
                  <button class="btn btn-danger btn-sm" (click)="cancel(s.id)">✕ Cancel</button>
                </div>
              </div>
              <div style="text-align:right;flex-shrink:0">
                <div class="sub-price">{{ s.plan?.price }} {{ s.plan?.currency }}</div>
                <div class="sub-period">/{{ s.plan?.billingPeriod }}</div>
              </div>
            </div>
          }
        </div>
      }
    </div>

    <!-- Create modal -->
    @if (showCreate()) {
      <div class="overlay" (click)="closeOverlay($event, 'create')">
        <div class="modal">
          <div class="modal-header">
            <div class="modal-title">New subscription</div>
            <button class="btn btn-ghost btn-sm" (click)="showCreate.set(false)">✕</button>
          </div>
          <div class="form-group">
            <label class="form-label">Service</label>
            <select class="form-select" [(ngModel)]="selectedServiceId" (ngModelChange)="loadPlans($event)">
              <option value="">Select a service…</option>
              @for (s of services(); track s.id) {
                <option [value]="s.id">{{ s.name }}</option>
              }
            </select>
          </div>
          @if (plans().length > 0) {
            <div class="form-group">
              <label class="form-label">Plan</label>
              <select class="form-select" [(ngModel)]="selectedPlanId">
                <option value="">Select a plan…</option>
                @for (p of plans(); track p.id) {
                  <option [value]="p.id">{{ p.name }} — {{ p.price }} {{ p.currency }}/{{ p.billingPeriod }}</option>
                }
              </select>
            </div>
          }
          <div class="form-group">
            <label style="display:flex;align-items:center;gap:8px;cursor:pointer;font-size:13px">
              <input type="checkbox" [(ngModel)]="newAutoRenew"> Enable auto-renew
            </label>
          </div>
          <div class="modal-footer">
            <button class="btn btn-ghost" (click)="showCreate.set(false)">Cancel</button>
            <button class="btn btn-primary" (click)="create()" [disabled]="!selectedPlanId">Create</button>
          </div>
        </div>
      </div>
    }

    <!-- Events modal -->
    @if (showEvents()) {
      <div class="overlay" (click)="closeOverlay($event, 'events')">
        <div class="modal">
          <div class="modal-header">
            <div class="modal-title">Subscription history</div>
            <button class="btn btn-ghost btn-sm" (click)="showEvents.set(false)">✕</button>
          </div>
          @if (events().length === 0) {
            <div class="empty"><div class="empty-icon">📋</div>No events recorded</div>
          } @else {
            <div class="table-wrap">
              <table>
                <thead><tr><th>Event</th><th>Date</th><th>Days</th></tr></thead>
                <tbody>
                  @for (e of events(); track e.id) {
                    <tr>
                      <td><span class="badge badge-purple">{{ e.eventType }}</span></td>
                      <td>{{ e.eventDate }}</td>
                      <td>{{ e.days ?? '—' }}</td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          }
        </div>
      </div>
    }

    <!-- Devices modal -->
    @if (showDevicesModal()) {
      <div class="overlay" (click)="closeOverlay($event, 'devices')">
        <div class="modal">
          <div class="modal-header">
            <div class="modal-title">Devices — {{ activeSub()?.plan?.service?.name }}</div>
            <button class="btn btn-ghost btn-sm" (click)="showDevicesModal.set(false)">✕</button>
          </div>

          <!-- Attached -->
          @if (subDevices().length === 0) {
            <div class="empty"><div class="empty-icon">📱</div>No devices attached yet</div>
          } @else {
            <div style="margin-bottom:16px">
              <div class="section-label" style="margin-bottom:8px">Attached</div>
              @for (d of subDevices(); track d.id) {
                <div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border)">
                  <div>
                    <div style="font-weight:500;font-size:13px">{{ d.name }}</div>
                    <div style="font-size:11px;color:var(--muted)">{{ d.type }}</div>
                  </div>
                  <button class="btn btn-danger btn-sm" (click)="detach(d.id)">Detach</button>
                </div>
              }
            </div>
          }

          <!-- Available -->
          @if (availableDevices().length > 0) {
            <div class="divider"></div>
            <div class="section-label" style="margin-bottom:8px">
              Available
              @if (activeSub()?.plan?.maxDevices) {
                <span style="color:var(--muted);font-weight:400;margin-left:8px">
                  ({{ subDevices().length }}/{{ activeSub()!.plan.maxDevices }} slots used)
                </span>
              }
            </div>
            @for (d of availableDevices(); track d.id) {
              <div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border)">
                <div>
                  <div style="font-weight:500;font-size:13px">{{ d.name }}</div>
                  <div style="font-size:11px;color:var(--muted)">{{ d.type }}</div>
                </div>
                <button
                  class="btn btn-primary btn-sm"
                  (click)="attach(d.id)"
                  [disabled]="!!activeSub()?.plan?.maxDevices && subDevices().length >= activeSub()!.plan.maxDevices!"
                >Attach</button>
              </div>
            }
          }
        </div>
      </div>
    }
  `
})
export class SubscriptionsComponent implements OnInit {
  private api   = inject(ApiService);
  private toast = inject(ToastService);

  loading    = signal(true);
  subs       = signal<Subscription[]>([]);
  services   = signal<Service[]>([]);
  plans      = signal<Plan[]>([]);
  events     = signal<SubscriptionEvent[]>([]);
  subDevices = signal<Device[]>([]);
  myDevices  = signal<Device[]>([]);
  activeSub  = signal<Subscription | null>(null);
  activeSubId = signal<number | null>(null);

  showCreate       = signal(false);
  showEvents       = signal(false);
  showDevicesModal = signal(false);

  selectedServiceId = '';
  selectedPlanId    = '';
  newAutoRenew      = true;

  attachedIds = computed(() => new Set(this.subDevices().map(d => d.id)));
  availableDevices = computed(() => this.myDevices().filter(d => !this.attachedIds().has(d.id)));

  ngOnInit() { this.load(); }

  load(showLoader = true) {
    if (showLoader) this.loading.set(true);
    forkJoin([this.api.getSubscriptions(), this.api.getServices()]).subscribe({
      next: ([s, sv]) => { this.subs.set(s); this.services.set(sv); },
      error: e => this.toast.error(e.error?.message ?? 'Error'),
      complete: () => this.loading.set(false)
    });
  }

  openCreate() {
    this.selectedServiceId = ''; this.selectedPlanId = ''; this.plans.set([]); this.newAutoRenew = true;
    this.showCreate.set(true);
  }

  loadPlans(serviceId: string) {
    if (!serviceId) { this.plans.set([]); return; }
    this.api.getServicePlans(+serviceId).subscribe({ next: d => this.plans.set(d) });
  }

  create() {
    this.api.createSubscription({ planId: +this.selectedPlanId, autoRenew: this.newAutoRenew }).subscribe({
      next: () => { this.toast.success('Subscription created'); this.showCreate.set(false); this.load(false); },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  toggle(id: number) {
    this.api.toggleAutoRenew(id).subscribe({
      next: () => { this.toast.success('Auto-renew updated'); this.load(false); },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  cancel(id: number) {
    if (!confirm('Cancel this subscription?')) return;
    this.api.cancelSubscription(id).subscribe({
      next: () => { this.toast.success('Subscription cancelled'); this.load(false); },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  viewEvents(id: number) {
    this.api.getSubscriptionEvents(id).subscribe({
      next: d => { this.events.set(d); this.showEvents.set(true); },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  openDevices(subId: number, sub: Subscription) {
    this.activeSubId.set(subId);
    this.activeSub.set(sub);
    forkJoin([this.api.getDevicesBySubscription(subId), this.api.getDevices()]).subscribe({
      next: ([attached, all]) => { this.subDevices.set(attached); this.myDevices.set(all); this.showDevicesModal.set(true); },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  attach(deviceId: string) {
    const subId = this.activeSubId()!;
    this.api.attachDevice(subId, { deviceId }).subscribe({
      next: () => {
        this.toast.success('Device attached');
        this.api.getDevicesBySubscription(subId).subscribe({ next: d => this.subDevices.set(d) });
      },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  detach(deviceId: string) {
    const subId = this.activeSubId()!;
    this.api.detachDevice(subId, deviceId).subscribe({
      next: () => {
        this.toast.success('Device detached');
        this.api.getDevicesBySubscription(subId).subscribe({ next: d => this.subDevices.set(d) });
      },
      error: e => this.toast.error(e.error?.message ?? 'Error')
    });
  }

  closeOverlay(e: MouseEvent, modal: string) {
    if (!(e.target as HTMLElement).classList.contains('overlay')) return;
    if (modal === 'create')  this.showCreate.set(false);
    if (modal === 'events')  this.showEvents.set(false);
    if (modal === 'devices') this.showDevicesModal.set(false);
  }
}
